defaults:
  - model_checkpoint
  - early_stopping
  - model_summary
  # - rich_progress_bar
  - _self_

model_checkpoint:
  # dirpath: ${paths.output_dir}/checkpoints
  dirpath: checkpoints
  filename: "epoch_{epoch:03d}"
  monitor: "val/loss" # name of the logged metric which determines when model is improving
  mode: "min" # can be "max" or "min"
  save_top_k: 1 # save k best models (determined by above metric)
  save_last: True # additionaly always save model from last epoch
  verbose: True
  auto_insert_metric_name: False

log_f1_precision_recall_heatmap:
  _target_: src.callbacks.wandb_callbacks.LogF1PrecRecHeatmap

# log_confusion_matrix:
#   _target_: src.callbacks.wandb_callbacks.LogConfusionMatrix

log_all_metrics:
  _target_: src.callbacks.wandb_callbacks.LogAllMetrics

# Model efficiency metrics
log_model_efficiency:
  _target_: src.callbacks.wandb_callbacks.LogModelEfficiency

# Variable importance logger
log_variable_importance:
  _target_: src.callbacks.wandb_callbacks.LogVariableImportance
  dynamic_features: ${sel_dynamic_features}
  static_features: ${sel_static_features}
